spring:
  application:
    name: crm2026

  #配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gbcs2025?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  #spring web静态资源路径
  web:
    resources:
      static-locations: classpath:/resources/, classpath:/static/, file:/${upload.location}
  #redis配置
  data:
    redis:
      password: 123456

#配置mybatis-plus
mybatis-plus:
  configuration:
    log-prefix: mybatis.
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    cache-enabled: false
  type-aliases-package: com.situ.crm2026.model
  mapper-locations: classpath*:/mapper/**/*.xml

server:
  port: 8080

#打印sql日志
logging:
  level:
    mybatis: debug


#文件上传存储路径
upload:
  location: d:/crm2026/upload/

#jwt密钥
jwt:
  secret: IbrK0GhQV8/HB/cihG7RgiuO0+1E51KkNVpjDfLNHVxFmRuj6zem0sPTMyjc3zk4


